@baseurl = http://localhost:3000

### GET all tasks
GET {{baseurl}}/tasks

### Create a new product
POST {{baseurl}}/tasks
Content-Type: application/json

{
    "title": "foo"
}

### Update a task
PUT {{baseurl}}/tasks/1
Content-Type: application/json

{
    "title": "bar",
    "completed": true
}

### Delete a task
DELETE {{baseurl}}/tasks/1

### 404 handler
GET {{baseurl}}/notfound